export const PacketType = {
  // Sync Lifecycle
  SYNC_START: 0x11,
  SYNC_FINISH: 0x12,
  SP_TYPE_EVENT: 0x13,
  SYNC_BATCH: 0x14,
  SYNC_CATEGORY_BATCH: 0x15,

  // Chat
  CHAT_MESSAGE: 0x18,

  // Listeners
  LISTENER_REG: 0x31,
  LISTENER_START: 0x32,
  LISTENER_STOP: 0x33,
  LISTENER_EDIT: 0x34,

  // Agent
  AGENT_REG: 0x41,
  AGENT_NEW: 0x42,
  AGENT_TICK: 0x43,
  AGENT_UPDATE: 0x44,
  AGENT_LINK: 0x45,
  AGENT_REMOVE: 0x46,

  // Tasks
  AGENT_TASK_SYNC: 0x49,
  AGENT_TASK_UPDATE: 0x4a,
  AGENT_TASK_SEND: 0x4b,
  AGENT_TASK_REMOVE: 0x4c,
  AGENT_TASK_HOOK: 0x4d,

  // Downloads
  DOWNLOAD_CREATE: 0x51,
  DOWNLOAD_UPDATE: 0x52,
  DOWNLOAD_DELETE: 0x53,

  // Tunnels
  TUNNEL_CREATE: 0x57,
  TUNNEL_EDIT: 0x58,
  TUNNEL_DELETE: 0x59,

  // Screenshots
  SCREEN_CREATE: 0x5b,
  SCREEN_UPDATE: 0x5c,
  SCREEN_DELETE: 0x5d,

  // Browser
  BROWSER_DISKS: 0x61,
  BROWSER_FILES: 0x62,
  BROWSER_STATUS: 0x63,
  BROWSER_PROCESS: 0x64,

  // Agent Console
  AGENT_CONSOLE_OUT: 0x69,
  AGENT_CONSOLE_TASK_SYNC: 0x6a,
  AGENT_CONSOLE_TASK_UPD: 0x6b,

  // Pivots
  PIVOT_CREATE: 0x71,
  PIVOT_DELETE: 0x72,

  // Credentials
  CREDS_CREATE: 0x81,
  CREDS_EDIT: 0x82,
  CREDS_DELETE: 0x83,
  CREDS_SET_TAG: 0x84,

  // Targets
  TARGETS_CREATE: 0x87,
  TARGETS_EDIT: 0x88,
  TARGETS_DELETE: 0x89,
  TARGETS_SET_TAG: 0x8a,

  // File Delivery
  FILEDELIVERY_CREATE: 0x91,
  FILEDELIVERY_UPDATE: 0x92,
  FILEDELIVERY_DELETE: 0x93,
};
