function GetConfig()
{
    var config = {
        "name": "Beacon DoH",
        "type": "listener",
        "author": "Adaptix",
        "version": "1.0",
        "description": "DNS Authority Listener (RFC 8484) for public DoH/recursive resolvers. Encapsulates DNS packets in HTTPS POST requests to bypass filtering.",
        "options": [
            {
                "name": "host_bind",
                "description": "Local interface to bind for DNS (UDP/TCP) used by public DoH/recursive resolvers",
                "type": "string",
                "default": "0.0.0.0",
                "required": true
            },
            {
                "name": "port_bind",
                "description": "Authoritative DNS port (53 recommended when used behind public DoH)",
                "type": "int",
                "default": "53",
                "required": true
            },
            {
                "name": "ssl",
                "description": "Enable SSL (HTTPS)",
                "type": "bool",
                "default": "true",
                "required": true
            },
            {
                "name": "ssl_cert",
                "description": "SSL Certificate",
                "type": "file",
                "default": "",
                "required": false
            },
            {
                "name": "ssl_key",
                "description": "SSL Private Key",
                "type": "file",
                "default": "",
                "required": false
            },
            {
                "name": "uri",
                "description": "DoH Endpoint URI",
                "type": "string",
                "default": "/dns-query",
                "required": true
            },
            {
                "name": "domain",
                "description": "Authoritative Domain Name (e.g. ns1.c2.com)",
                "type": "string",
                "default": "",
                "required": true
            },
            {
                "name": "doh_urls",
                "description": "DoH Provider URLs (Comma separated)",
                "type": "string",
                "default": "https://dns.google/dns-query,https://cloudflare-dns.com/dns-query",
                "required": true,
                "long": true
            },
            {
                "name": "user_agent",
                "description": "User-Agent for DoH Requests",
                "type": "string",
                "default": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                "required": true
            },
            {
                "name": "pkt_size",
                "description": "Max DNS Payload Size (bytes). 4096+ recommended for DoH.",
                "type": "int",
                "default": "4096",
                "required": true
            },
            {
                "name": "ttl",
                "description": "DNS TTL (Seconds)",
                "type": "int",
                "default": "5",
                "required": true
            },
            {
                "name": "encrypt_key",
                "description": "Encryption Key (Autogenerated)",
                "type": "string",
                "default": "random_hex_32",
                "required": true,
                "hidden": false
            },
             {
                "name": "mode",
                "description": "Listener Mode (authoritative only for now)",
                "type": "select",
                "default": "authoritative",
                "values": ["authoritative"],
                "required": true
            }
        ]
    };
    return config;
}
